name: Publish GitHub Action

on:
  push:
    branches:
      - main  # or 'master' if that's your default branch name

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Publish GitHub Action
        uses: dylanvann/publish-github-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}