name: Test and Publish GitHub Action

on:
  push:
    branches:
      - main

jobs:
  test-and-publish:
    name: Test and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # or whichever version you're using

      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npm run build  # Assuming you have a build script in package.json

      - name: Run tests
        run: npm test

      - name: Publish GitHub Action
        if: success()  # Only publish if all previous steps succeeded
        uses: dylanvann/publish-github-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}